tipo:Diesel Max Pro:9100:210.0
tipo:Extra:19600:190.0
tipo:Corriente:15870:229.9990548204159
tipo:Diesel:8400:250.0
surtidor:Nicolas:Diesel Max Pro:0.0:Extra:0.0:Corriente:0.0:Diesel:0.0
surtidor:Juan:Diesel Max Pro:0.0:Extra:10.0:Corriente:0.0:Diesel:0.0
surtidor:Felipe:Diesel Max Pro:0.0:Extra:0.0:Corriente:0.0:Diesel:0.0
surtidor:Nicolas:Diesel Max Pro:0.0:Extra:0.0:Corriente:9.45179584120983E-4:Diesel:0.0
empleado:Samuel:0
empleado:Felipe:0
empleado:Jaime:0
empleado:Juan:196000
empleado:Nicolas:15
